name: Delete Older Release Assets
description: delete older release assets of any repo
author: tinoji

branding:
  color: red
  icon: trash-2

inputs:
  keep_latest:
    description: how many latest releases to keep
    required: true
  repo:
    description: repo name in the form of <owner>/<repoName>
    required: false

runs:
  using: "node12"
  main: "index.js"
